#!/usr/bin/env python3
"""Generates src/VirtuaCam/NoSignalMask.h — an alpha mask of the "NO SIGNAL"
wordmark, rastered from the Selawik typeface (SIL OFL 1.1, (c) Microsoft).

The mask is what ships; the font itself is not embedded or redistributed.
Usage:  python3 tools/gen_nosignal_mask.py path/to/selawk.ttf
"""
import sys
from PIL import Image, ImageDraw, ImageFont

TEXT = "NO SIGNAL"
SUPERSAMPLE_PX = 256          # raster height of the glyphs before downsampling
TRACKING_EM = 0.32            # extra letter-spacing, as a fraction of font size
MASK_HEIGHT = 48              # final embedded mask height in pixels

def main(font_path: str, out_path: str) -> None:
    font = ImageFont.truetype(font_path, SUPERSAMPLE_PX)
    tracking = int(SUPERSAMPLE_PX * TRACKING_EM)

    # Measure total advance with tracking.
    widths = [int(font.getlength(ch)) for ch in TEXT]
    total_w = sum(widths) + tracking * (len(TEXT) - 1)
    canvas = Image.new("L", (total_w + SUPERSAMPLE_PX, SUPERSAMPLE_PX * 2), 0)
    draw = ImageDraw.Draw(canvas)

    x = SUPERSAMPLE_PX // 2
    for ch, w in zip(TEXT, widths):
        draw.text((x, SUPERSAMPLE_PX // 2), ch, fill=255, font=font)
        x += w + tracking

    bbox = canvas.getbbox()
    trimmed = canvas.crop(bbox)
    scale = MASK_HEIGHT / trimmed.height
    mask = trimmed.resize((max(1, int(trimmed.width * scale)), MASK_HEIGHT), Image.LANCZOS)

    data = mask.tobytes()
    with open(out_path, "w") as f:
        f.write("// Generated by tools/gen_nosignal_mask.py — do not edit by hand.\n")
        f.write('// Alpha mask of the "NO SIGNAL" wordmark, rastered from the Selawik\n')
        f.write("// typeface ((c) Microsoft Corporation, SIL Open Font License 1.1).\n")
        f.write("// Per the OFL, rendered text images carry no license obligations.\n")
        f.write("#pragma once\n\n")
        f.write(f"constexpr unsigned int kNoSignalMaskWidth  = {mask.width};\n")
        f.write(f"constexpr unsigned int kNoSignalMaskHeight = {mask.height};\n")
        f.write(f"constexpr unsigned char kNoSignalMask[{len(data)}] = {{\n")
        for i in range(0, len(data), 24):
            f.write("    " + ",".join(str(b) for b in data[i:i+24]) + ",\n")
        f.write("};\n")
    print(f"wrote {out_path}: {mask.width}x{mask.height}, {len(data)} bytes")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "selawk.ttf",
         "src/VirtuaCam/NoSignalMask.h")
